### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by ghost** [mbdevpl/transpyle#9] opened 2019-11-09 04:36 UTC
The concept and the use case is amazing.

Is this project still active?

**Comment by mbdevpl** [comment] 2019-11-11 04:57
Yes, by all means the project is active! Since the project as a whole is modular, and dependencies are in different repos, I can see why you didn't notice the updates :)

**Comment by ghost** [comment] 2019-11-13 17:11
@mbdevpl What are the links to those?

**Comment by mbdevpl** [comment] 2019-11-14 03:18
Closest related one that recently I've been working on improving is code comment read/write support in Python AST, through module https://github.com/mbdevpl/horast

**Comment by mbdevpl** [comment] 2019-11-14 03:28
Also, if you see requirements there's also static-typing (ahead-of-run type resolution for Python), typed-astunparse (generation of Python code with type comments) and open-fortran-parser (well, parsing Fortran code) that I've been developing with transpyle as main project in mind.

**Comment by ghost** [comment] 2019-11-15 22:01
@mbdevpl I want to start contributing but I don't know how. There are not many issues listed. Do you have any suggestions for that?

**Comment by mbdevpl** [comment] 2019-11-27 22:48
Hi! Sorry for delay in the reply. If you're using Mac, or Windows, I'd say an interesting issue to work on is improving compatibility with those platforms. I have set up CI for those, but the amount of tests that pass is less than for Linux. And on top of it, CI seems to be having their own issues that I couldn't reproduce.

For example I even had issues with getting compilers installed through brew on Travis CI to work with the project, while on my Macbook (while I still had it) they just worked. It might be that the problem is with Travis CI setup, or my framework implementation has some internal compatibility issues that show up only on Travis. Either way, I'd like to make the framework as much cross-platform as possible.

If you're using Linux, then I'd say finding small code examples that don't translate correctly would be a worthy task. As you say, there are not many issues listed, but if you find any concrete small code example that should be translatable but translates incorrectly or causes errors in the transpiler, I'd appreciate you letting me know about it. I think such test-driven approach would speed up transpiler improvements.

**Comment by mbdevpl** [comment] 2020-01-29 07:22
Closing this because the conversation seems to have ended. If you have any specific question about how to use transpyle, or you encounter any problems/bugs when using, or have any new ideas about how to improve it, please open new issue or a PR. Thanks!

**Closed as completed by mbdevpl** 2020-01-29 07:22 UTC
